
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kalimaya-storage-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/kalimaya-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kalimaya-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
