// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kruuhpqjopsfmnjcsuyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydXVocHFqb3BzZm1uamNzdXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzgzMDcsImV4cCI6MjA2MDYxNDMwN30.kHx84VIGgxgFAve6wcIB3u016J9peLE7VI_S2qbD_lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);